global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jobmatcher-server'
    static_configs:
      - targets: [ 'localhost:8080' ]
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    basic_auth:
      username: 'yourusername'
      password: 'yourpassword'

  - job_name: 'k6'
    static_configs:
      - targets: [ 'localhost:6565' ]
